trigger: none

pool:
  name: Default

variables:
- group: Terraform_SPN

  

stages:
- stage: Terraform
  jobs:
  - job: TerraformJob
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '~> 1.9.8'

    - script: |
        terraform init
      displayName: 'Terraform Init'

    - script: |
        terraform plan -out=tfplan
      displayName: 'Terraform Plan'

    - script: |
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)